//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmyTechTask.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class InvoiceDetails
    {
        public long ID { get; set; }
        [Required]
        [Display(Name = "Customer Name")]
        public long InvoiceHeaderID { get; set; }
        [Required]
        [Display(Name = "Item")]

        public string ItemName { get; set; }
        [Required]
        [Display(Name = "Quantity")]
        [DataType(DataType.PhoneNumber)]
        public double ItemCount { get; set; }
        [Required]
        [Display(Name = "Price")]
        [DataType(DataType.PhoneNumber)]
        public double ItemPrice { get; set; }

        public virtual InvoiceHeader InvoiceHeader { get; set; }
    }
}
